services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: apex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - apex_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  apex_network:
